server.port=8082

spring.application.name=ms-pacientes

spring.datasource.url=jdbc:mysql://medictime-rds.cdnlox5sl91y.us-east-1.rds.amazonaws.com:3306/pacientes_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=MedicTime2026!

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.microservicios=DEBUG
logging.level.org.springframework.security=DEBUG

# 🔐 CONFIGURACIÓN JWT
jwt.secret=miClaveSuperSecretaJWT_2026_segura_1234567890
jwt.expiration=86400

server.error.whitelabel.enabled=false

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG